name: SkillPaths
version: ${project.version}
main: dev.floffah.skillpaths.SkillPaths
api-version: 1.15
depend: [Vault]
authors: [Floffah]
description: A skill paths plugin inspired by mcMMO
commands:
  skills:
    description: SkillPaths
    aliases: [sp,skillpath,skillpaths,skill,paths,path]