name: SkillPaths
version: ${project.version}
main: dev.floffah.skillpaths.SkillPaths
api-version: 1.15
depend: [FloffahUtil, Vault, HeadDatabase]
authors: [Floffah]
description: A skill paths plugin inspired by mcMMO
commands:
  skillpaths:
    description: SkillPaths
    aliases: [sp,skillpath,skillpaths,skills,skill,paths,path]