on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main


jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 1.8 set up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build javadoc
        env:
          USENAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: "mvn --settings settings.xml javadoc:javadoc"
      - name: Move javadoc
        run: mv -v target/site/apidocs docs/
      - uses: EndBug/add-and-commit@v5
        with:
          add: '.'
          author_name: GitHub Actions
          message: "github actions javadoc build"